export const ON_FETCH_POSTS_LOADING = 'ON_FETCH_POSTS_LOADING';
export const ON_FETCH_NEW_POSTS_SUCCESS = 'ON_FETCH_NEW_POSTS_SUCCESS';
export const ON_FETCH_OLD_POSTS_SUCCESS = 'ON_FETCH_OLD_POSTS_SUCCESS';
export const ON_FETCH_POSTS_FAILURE = 'ON_FETCH_POSTS_FAILURE';
